version: '2'
services:
  nginx:
    build:
      context: ./images/nginx
    volumes:
      - ./../www:/var/www
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/sites/:/etc/nginx/sites-available
      - ./images/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    links:
      - php
    ports:
      - "80:80"
      - "443:443"

  php:
    build: ./images/php
    volumes:
      - ./../www:/var/www
